services:

  opensearch_sef:
    build: .
    container_name: opensearch_sef
    environment:
      discovery.type: single-node
      node.name: opensearch
      plugins.security.disabled: "true"
      logger.level: info
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: SuperSecretPassword_123
      http.max_content_length: 500mb
      OPENSEARCH_JAVA_OPTS: "-Xms8g -Xmx8g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net
    volumes:
      - opensearch-data1:/usr/share/opensearch/data

  opensearch_sef_dashboards:
    image: opensearchproject/opensearch-dashboards:2.18.0
    container_name: opensearch_sef_dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch_sef:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      - opensearch_sef
    networks:
      - opensearch-net

volumes:
  opensearch-data1:

networks:
  opensearch-net:
    driver: bridge
