name: Build and Test
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        jdk: [ 21 ]
        experimental: [false]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: ${{ matrix.jdk }}
      - name: Build
        run: mvn --batch-mode test